name: ESP32 CI/CD

# Triggers the workflow on pull request to main or any push to remote
on:
  pull_request:
    branches:
      - main
  push:

# Defines jobs to be run
jobs:
  build:
    # Specifies the runner, in this case, Ubuntu
    runs-on: ubuntu-latest

    # Steps that the job will execute
    steps:
      # Checks out the code from the repository, always needed
      - name: Checkout code
        uses: actions/checkout@v4

      # Uses the official ESP-IDF action to build the project
      - name: ESP-IDF Build
        uses: espressif/esp-idf-ci-action@v1
        with:
          # Version of ESP-IDF to be used, default is the latest version
          esp_idf_version: 'v5.3.1'
          # Target type of ESP32, default is esp32 (can change to esp32s3 or others)
          # target: esp32s3
          # Path to the project to be built relative to the root of the repository
          # path: example/project
          # Command to run for the build, default is idf.py build
          # Can be overridden to include other steps, e.g.:
          # command: idf.py build && python3 example_script.py